version: '2'
services:
  rpc:
    build:
      context: ./
      dockerfile: rpc.Dockerfile
    ports:
      - 8545

  workspace:
    build:
      context: ./
      dockerfile: workspace.Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/workspace
